

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: pihole-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.16.1
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    envFrom:
      - secretRef:
          name: &secret external-dns-pihole-secret
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://172.16.20.7
    # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
    # You don't need to set this flag, but if you leave it unset, you will receive warning
    # logs when ExternalDNS attempts to create TXT records.
    registry: noop
    # IMPORTANT: If you have records that you manage manually in Pi-hole, set
    # the policy to upsert-only so they do not get deleted.
    policy: upsert-only
    log-level: debug
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --ignore-ingress-tls-spec
      - --events
    sources:
      - "crd"
      - "gateway-httproute"
      - "gateway-tlsroute"
      - "gateway-tcproute"
      - "gateway-udproute"
    domainFilters: ["rphilipsen.nl"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
