---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pihole: &controller
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          pihole: &container
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.17.0
            env:
              - name: EXTERNAL_DNS_PIHOLE_SERVER
                value: http://172.16.20.7
            envFrom:
              - secretRef:
                  name: *app
            args:
              - --source=ingress
              - --source=service
              - --registry=noop
              - --ignore-ingress-tls-spec
              - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
              - --crd-source-kind=DNSEndpoint
              - --source=gateway-httproute
              - --source=gateway-tlsroute
              - --source=gateway-tcproute
              - --source=gateway-udproute
              - --events
              - --provider=pihole
              - --pihole-api-version=6
              - --interval=5m
              - --log-format=text
              - --log-level=debug
              - --metrics-address=:7979
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    serviceAccount:
      create: true
      name: *app
    service:
      pihole:
        controller: pihole
        ports:
          http:
            port: *port
    serviceMonitor:
      pihole:
        serviceName: external-dns-pihole
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s