---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    serviceAccount:
      external-dns-pihole: {}

    controllers:
      pihole: &controller
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          identifier: external-dns-pihole
        containers:
          pihole: &container
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.18.0
            env:
              - name: EXTERNAL_DNS_PIHOLE_SERVER
                value: http://172.16.20.7
            envFrom:
              - secretRef:
                  name: external-dns-pihole-secret
            args:
              - --source=ingress
              - --source=service
              # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
              # You don't need to set this flag, but if you leave it unset, you will receive warning
              # logs when ExternalDNS attempts to create TXT records.
              - --registry=noop
              # IMPORTANT: If you have records that you manage manually in Pi-hole, set
              # the policy to upsert-only so they do not get deleted.
              - --policy=upsert-only
              - --ignore-ingress-tls-spec
              - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
              - --crd-source-kind=DNSEndpoint
              - --source=gateway-httproute
              - --source=gateway-tlsroute
              - --source=gateway-tcproute
              - --source=gateway-udproute
              - --events
              - --provider=pihole
              - --pihole-api-version=6
              - --interval=5m
              - --log-format=text
              - --log-level=debug
              - --metrics-address=:7979
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true

    service:
      pihole:
        controller: pihole
        ports:
          http:
            port: *port
    serviceMonitor:
      pihole:
        serviceName: external-dns-pihole
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s