---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-pihole-secret
            key: EXTERNAL_DNS_PIHOLE_SERVER
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: *secret
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
      - name: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
        valueFrom:
          secretKeyRef:
            name: *secret
            key: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        valueFrom:
          secretKeyRef:
            name: *secret
            key: EXTERNAL_DNS_PIHOLE_API_VERSION
    extraArgs:
      - --pihole-api-version=6
      - --metrics-address=:7979
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    triggerLoopOnEvent: true
    policy: upsert-only
    sources:
      - "crd"
      - "gateway-httproute"
      - "service"
    txtPrefix: k8s.
    txtOwnerId: default
    logLevel: debug
    logFormat: text
    domainFilters:
      - rphilipsen.nl
      - philipsen.it
      - trees100.nl
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-pihole-secret
