---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://172.16.20.7
    envFrom:
      - secretRef:
          name: &secret external-dns-pihole-secret
    extraArgs:
      - --pihole-api-version=6
      - --metrics-address=:7979
    triggerLoopOnEvent: true
    policy: upsert-only
    sources:
      - "crd"
      - "gateway-httproute"
      - "service"
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters:
      - rphilipsen.nl
      - philipsen.it
      - trees100.nl
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
