---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: prometheus
    orgId: 1
    name: prometheus
    access: proxy
    isDefault: true
    url: http://vmsingle-vmetrics.observability.svc.cluster.local:8428
    jsonData:
      timeInterval: 1s
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: alertmanager
    orgId: 1
    name: alertmanager
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://alertmanager-vmetrics.observability.svc.cluster.local:9093
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-traces
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: jaeger
    orgId: 1
    uid: victoria-traces
    name: victoria-traces
    access: proxy
    url: http://victoria-traces-server.observability.svc.cluster.local:10428/select/jaeger
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: victoriametrics-logs-datasource
    orgId: 1
    uid: victoria-logs
    name: victoria-logs
    access: proxy
    url: http://victoria-logs-server.observability.svc.cluster.local:9428
