---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: 0
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 0
  uninstall:
    keepHistory: false
  dependsOn:
      - name: intel-device-plugin-gpu
        namespace: kube-system
  values:
    defaultPodOptions:
      enableServiceLinks: false
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: false
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups: [160, 140, 241, 0, 10, 121, 44, 65537]
      hostNetwork: false

    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.10.7
              pullPolicy: Always

            env:
              TZ: ${TIMEZONE}
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_PublishedServerUrl: &url "{{ .Release.Name }}.${SECRET_DOMAIN}"

            securityContext:
              privileged: true

            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3

              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
            resources:
              requests:
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                # memory: 8Gi

    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: *url
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: jellyfin

      data:
        existingClaim: media-nfs

      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
