---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: semversie-
resources:
  - ../base
patches:
  - path: ./helmrelease.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: runner
  - patch: |-
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: runner
      spec:
        target:
          name: semversie-runner-secret
    target:
      kind: ExternalSecret
      name: runner
  - patch: |-
      - op: replace
        path: /subjects/0/name
        value: semversie-runner
    target:
      kind: ClusterRoleBinding
      name: runner
