---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sable
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sable

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: false
        seccompProfile: { type: RuntimeDefault }
      hostNetwork: false

    controllers:
      sable:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/sableclient/sable
              tag: 1.17.0
              pullPolicy: IfNotPresent

            securityContext:
              privileged: false

            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3

              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30

    service:
      app:
        controller: sable
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames: ["sable.rphilipsen.nl"]
        parentRefs:
          - name: agentgateway-internal
            namespace: network
            sectionName: https
          - name: agentgateway-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
