---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      esphome:
        pod:
          hostNetwork: true

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/esphome
              tag: 2025.8.1

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                cpu: 20m
                memory: 64M
              limits:
                memory: 1024M

    service:
      esphome:
        controller: esphome
        ports:
          http:
            port: &esphome 6052
      lb:
        controller: esphome
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 172.16.20.131
        ports:
          ws:
            protocol: TCP
            port: *esphome
            primary: true
        externalTrafficPolicy: Cluster

    route:
      app:
        hostnames: ["{{ .Release.Name }}.rphilipsen.nl"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: rphilipsen-https
        rules:
          - backendRefs:
              - name: esphome-esphome
                port: *esphome
    persistence:
      config:
        type: nfs
        server: 172.16.20.7
        path: /config/esphome
        globalMounts:
          - path: /config
      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /cache
