# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:oE4XocNQkhBnS9i38zGqZVWQlHlVCdLrF5Zn6HAIUJUwdP7KbmlBNTFk1cedEcOQLyIh9oU3tx5ZrnQpSfj8xVe1DpojxBbwr8vJO6T8Xtyv9vBWFFL2zdQYRHtqjc4kyFPjV1WEMZBIyoQaO+02yWn14QG3LUVJwHY3F8uZZJrfSzflxHzqbrvADBu4b2Y+/8tVPXodRsxDd+LUeuKmz/u1bSPWbkC131/q/sRAaQLAZuMw/A==,iv:hN/F2JqH3ocwcwXVJtFA6It2bYxvmgCobmzIlAUT8zE=,tag:nZpUF987Ozul1+czAo/f8Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUEV5cXhRSTVoMFdJN0dF
        d040SGhjYld5RE1mY2xIazdwNFNtMWw5blF3CnU2VGZlMzhISC81SFdRYzhGRnJQ
        V1hybUI1NEhxalUyM3hoZ1ZFQUJYVEkKLS0tIFRac2hyemV5cUpsdXJyM2pCY3BD
        eW9zMDRueDFaaHJSTURzbWQvVWE0ZjAKtVuFDkJDA6OzBh4tTJZnJZodd807PaFv
        upBcHli0FJrYp1cdRUJrsOFBNbszybIdhxiCX0wioIHiWmGn3ocCRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-19T17:17:54Z"
  mac: ENC[AES256_GCM,data:oifK0UF+q9iTylkamEM1M8camTIs9dlZcedL8xVBKpSGWzgXl6VZZFYs/lCCycWOGsTlqElsG+qspIniN5Wa6WxalF2Q7LsB3g18o374NixevFHI/CrI5Y9XTY500oZqptDjNm0CIcWT+V1g56i82c1ZO++KP/8O4PqpxrnY1vM=,iv:K7fhe+IBWN3y3upbH/ZOoE5aK3F1N67iIyEOutxBezk=,tag:+H5fOEgLGVn0zXlQQ2+bAw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
