# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:AV2TLmzJBfvVpki9NwljA/gk0zL19vt53K5EDgRsR6cyLp1fmFpcqb+0jeUbwAJfZMM+0rDOA0SdKxMbFkyqOBKVhlLdnf4Eg786URfw+B4PxQ+0R4Ige6ESL2Ze4P8gkGJt1e9DWzrblhfkQ7m0fonvz7/yYaExpnG4n/7I1hZ5gQIo0VvH1jI9hdYSp/deu3d9v6+lhQEJ+lBIrsHUQRhZSu1xrnHHXAAg1aZOiDpyqSTpkQ==,iv:lBhqlYnhHatFyX/mWnfQynnpiZAztBXSoU5aXu8Pfu8=,tag:OV3ThDpvVuy4gClWl0uWsw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdlB3S1A4KzNUUnJQaHhN
        SStaSlVOK0pGOFV5VFo2MHdLcFZhOHlqTFZVCmp4d1llVGhWRkJ4ajJreVkyRUxC
        ZlRBdGQ5Z2Z6OVpXendjbzllckZibVkKLS0tIHBJMWhtSzMzaDc4QkVualhwRjVv
        czA1d243dENJdExvMWZhQThqbjBVZU0KB9T5QvP7rROeg4dCJJq28J56WV3Qpk8Y
        DBn8YJ5s9FaZOl7wgoSoL0RBSRR83pDu2H0D+3jvAqMciQPuBujqVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T20:12:37Z"
  mac: ENC[AES256_GCM,data:Xvo0FrKhXkXiYidszeAo/Z+miNm4KZ4CetoEN1uaKhYrD4RaA4Mn77mvx4HXPZjj1xDphCMuatgoH/EU8bm8PDWM4zifssK7I3ysRymDeUfLqmbqwHuCy1MwR4mUSNZRq6LrvPegg1F33Oh3UX0x+AhSNe63h9+S/I53kgDMEmo=,iv:Hba+QS7djNUTFYma/fY5Z2IZ0pF77sME5CewEs1ZXG8=,tag:/bTxb5icG12GK2Ox06eieg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
