# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:rOzjZEmBYiHDlXLsep7iRceiTbt8WwbAQuj+exeMGgOIOWpcN1iZAa+aDM0lmTsqfxLUNTaI7WK8tx2BjaM655nc50oxCy8IxWFG/gCy/KGMevGjCrxYRfMc7x6iWImeGwaYR9Jj3rTYYdkRWK3rZ+bvpQK2ZFbLs2in5BEN0Ktenf98rSDOEUj6frQ4LqZrXgxMAbK488YZpUKTO4BbExEneR2wTQNSEqs1tZQ5dXAwtFPowA==,iv:1b7B6UwL3/Ysc5rxmGjjv0hSWNHhkC7aROx22sbsndc=,tag:7TRyJfp+gp86Du5BcZbfgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2pSYjhJU2pKeURaOURu
            N08vNFlYSzhSZFZ0N2hsMVpyazZ4SjZjVEFBCndYdTkwQkFNalFWUEFyQTV0a0lK
            VHZMTC8wNFRoSHFpbHpmMGZhamZIYncKLS0tIEUweXhSV2YyVjFWeEc4RzVTTS9v
            dGdKOVpHMHBEazFUclRwM0NLb2QyWHcKIppAQRM3ds23fJ5hofiGlZOm+azqAk6V
            NJDLDIyIQQGFZwM0BtiwxZfUbeqKSmQ2coShzKoBzYqnFEshXbGyNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T20:17:32Z"
    mac: ENC[AES256_GCM,data:nraG7fzeTu/LaiE+tR4apsBt1iq48X7kQ+9dFSX60VsVDOuDQ8w2xSJ4qhV5A8Ol3Y3yQcBBzLQX9FX0X3oqtYudoatYyTBbKeplW0ZCFjcI0oxF+ChI0rTvaY0vShY+yPx2yTrpqB+X6BSa8qmBK8jlcVz3mMdPBlWQcpMBk+Q=,iv:VkKGnZZ/vtBsBDalIEPEtpMo47J1jKU+wAUsbvnFeNo=,tag:N1dIDPQF5fi3FJwo/7bdzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
