apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
data:
  EULA: "TRUE"
  VERSION: "1.21.3"
  MC_PORT: "25565"
  MEMORY: "4096M"
  MOTD: "Honk"
  OVERRIDE_ICON: "true"
  OPS: |-
    c251e7d8-ac28-4589-83c9-54b42cd2f878
  ICON: "https://opengameart.org/sites/default/files/Pixel_Bird_png.png"
  WORLD: "https://www.curseforge.com/api/v1/mods/674973/files/6194809/download"
  TZ: "Europe/Vienna"