apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
spec:
  replicas: 1
  serviceName: minecraft-server
  selector:
    matchLabels:
      server: minecraft-server
  template:
    metadata:
      labels:
        server: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          envFrom:
            - configMapRef:
                name: minecraft-server-config
          env: []
          image: itzg/minecraft-server:latest
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 150m
          livenessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 120
            periodSeconds: 60
          readinessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi