---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .MINECRAFT_SURVIVAL_USERNAME }}"
        password: "{{ .MINECRAFT_SURVIVAL_PASSWORD }}"
        whitelist: "{{ .MINECRAFT_SURVIVAL_WHITELIST }}"
        ops: "{{ .MINECRAFT_SURVIVAL_OPS }}"
        rcon_password: "{{ .MINECRAFT_SURVIVAL_RCON_PASSWORD }}"
  dataFrom:
    - extract:
        key: minecraft
