apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
data:
  EULA: "TRUE"
  # renovate: depName=minecraft datasource=custom.minecraft versioning=semver-coerced
  VERSION: "1.21.3"
  MC_PORT: "25565"
  MEMORY: "4096M"
  MOTD: "Honk"
  OVERRIDE_ICON: "true"
  ICON: "https://opengameart.org/sites/default/files/Pixel_Bird_png.png"
  WORLD: "https://www.curseforge.com/api/v1/mods/674973/files/6194809/download"
  TZ: "Europe/Amsterdam"
  SERVER_NAME: MPOF
  TYPE: FABRIC
  FORCE_REDOWNLOAD: "false"
  DIFFICULTY: hard
  SPAWN_PROTECTION: "0"
  SEED: "-2135836821937050197"
  FORCE_REDOWLOAD: "true"
  ENABLE_WHITELIST: "false"
  # Logging
  ENABLE_ROLLING_LOGS: "true"
  LOG_TIMESTAMP: "true"
  # Performance
  JVM_XX_OPTS: -XX:MaxRAMPercentage=75
  MAX_MEMORY: 8G
  USE_AIKAR_FLAGS: "true"
  SNOOPER_ENABLED: "false"
  VIEW_DISTANCE: "14"
  ## Mods
  REMOVE_OLD_MODS: "true"
  MODRINTH_DEFAULT_VERSION_TYPE: release
  MODRINTH_PROJECTS: >
    fabric-api,
    fabricexporter,
    spark,
    bluemap,
    geyser:beta,
    floodgate:beta
  # https://vanillatweaks.net/share#oNYxlz
  VANILLA_TWEAKS_SHARE_CODES: oNYxlz # Coord HUD, Anti-Endermen Griefing
