# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jzusSQGzpA2PK7jynp1BNZpgK2S/yVTqZWYfQ4I/fKJertP4WjWftQ==,iv:5aQ3gvQXZh9v9By/vtKjv6PqiyA6uEOEuBu8XJTF/xE=,tag:2SPyCiLRuXu6yd54OrixTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESkVESVN4UHJydU4rUDVp
        UHdNTk5sdnRiVWtwR0h3eHZMSlJtbzRvc3dnCnlLVFhBR3AyTXJZWFhzeitIVDFk
        N0RzODk2RExIVVRlQlRsMUJMa0wwZEEKLS0tIElMV2t5bC9aOEJtaGI5czZrRmht
        dlVBMnl6U2sxL1IxcGdFdHBZTm5vdm8KUCCL5+HGlxN/e/FDhtvwIZbv6Hdk0iYh
        f/5RcNw86+sLn5y6mQjHIv8htBX1+2+sBbQTtAUgPtHfHzGqoulctQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-19T17:17:54Z"
  mac: ENC[AES256_GCM,data:3TfRBtKk0qp5uObI4nhoe7PtgSwE5WvIJ/zzqkpru5xVHdoBgtGpoDD3b/WL6I/V1CpM/3pHfZ1ODXVzPRl9nwRl9IPgoJdFYwuoPGbEfRGzlSU+WC7wxAgk57HecVTyV09ay7hZ/wNgWWwxBi7+h5kz9nqHhVHg/sbwc+6Si+0=,iv:QqwRcSQto51/8hEXziiFthmUUdNcWW24R8WArVXJQd0=,tag:6fiKjI9Sy9M2CPoz22443w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
