# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: kopiur-repository
spec:
  externalSecretName: kopiur-repository
  namespaces:
    - actions-runner-system
    - default
    - home-automation
    - jellyfin
    - media
    - security
    - storage
  externalSecretSpec:
    refreshInterval: 12h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      name: kopiur-repository-secret
      creationPolicy: Owner
      template:
        data:
          KOPIA_PASSWORD: "{{ .RESTIC_PASSWORD }}"
    dataFrom:
      - extract:
          key: volsync-template
