---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-events-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-events-agent
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-events-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-events-agent
subjects:
  - kind: ServiceAccount
    name: otel-events-agent
    namespace: observability
