# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:75HvckztJXRaK29IlAuZnlRRR8UYchwmvZt5VSx5Q1T2ad3c1Vb9Nw==,iv:C/LoISD+9GmHP3Kc/37waDr4OD/R3qezCk3YI4N0l+k=,tag:7NRcmYVnSR1Tyh1lsu7FBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVnJwSEg4YzJpZDNwU3Bz
            MmsrR2wxNlBTMzFyNFNNMElUNXREQVVRaW1VClM4a1lSeVZjZ0NIbWh5RHA0L0d3
            ekVqUm5lR0d5b3BodXJPS0grRjE4a0UKLS0tIExacVg2Z0FnSm52SkI5Uys2clJ4
            UGpzcmQ5N2ZiZHk1S09kbmZSVHhnTGsKhdokN6abOWWJcXkqYCQ0vIII6qLdtnNT
            7sRAEjOBLi50ihcyx0OcP6+1DhOlowj+GjS+zbNOMNzjcE8qMwWnfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T20:20:33Z"
    mac: ENC[AES256_GCM,data:otyVUIBAbH6SVxDErczuKt15y3kREFgldgXEul8M6/FcwfZu2nWQGdy37BHhFoiJzS+i0zNpb5G9c4jsGBMbFJGKQtjclM9lmFFnOGSVGf9Qeb2hb7o//zAR4dPzcDQVh/An9TRdnr0O+RjqSR03c10zhsnKY4EBUqpVVDPlWrk=,iv:vL6MANbfv1utqwqyJVbPcDbU+Ph9ZBiIEwW3LjZ4quM=,tag:VC2G54L+WDykaI3GpV6BYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
