---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    template:
      engineVersion: v2
      data:
        RENOVATE_PLATFORM: 'github'
        RENOVATE_TOKEN: |-
          {{ .RENOVATE_GITHUB_PAT }}
        RENOVATE_GITHUB_COM_TOKEN: |-
          {{ .RENOVATE_GITHUB_PAT }}
        # You can set RENOVATE_AUTODISCOVER to true to run Renovate on all repos you have push access to
        RENOVATE_AUTODISCOVER: 'true'
        RENOVATE_ENDPOINT: 'https://github.com/api/v3'
  dataFrom:
    - extract:
        key: renovate