apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Vsx/yyl1JSt5Lo+13T1UStVFkwSqev/rlgm78tYzWTNyVOzF,iv:wfEPmlXmiCesiJOIec+jtwoIC97kmNPw59dDPdjx/3Y=,tag:2jIvcPHEVPX3sZmPpIYLkw==,type:str]
    credentials.json: ENC[AES256_GCM,data:E6xhmiBH00AD7Gmgn7j6j/LY9qE5Kgv2Lj54oaF50vFD8WvyTvKbTe2/zvKpH4AfsEh4ipLNhlSYxev0EfGpSx2NoE9JJZeSPolCGSeKn//VRfoXMNYSrpUEcX1xoq6P9+Omfz77gOigIByUw8WOG6X2daq/W82J1j1luYkF39JC50b2iZX9paiEp64Npu1MawRoekoo6iih5KipxZywEPiaF3wXcej2eKrhlnrQSA==,iv:yCvnGEXOjbD6VuONGyYulClkoegQfZaItJVSlqWQjsI=,tag:+brBvAXgLKGF8xFs2/O2Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVVYweHNjcENUS0MvM0Jj
            OU8yM2xTbzhFTGsydnVWd3lDNzhFSWExTEhBCjN5VXBNWXllTE00ajgwQkRoQ1Mw
            blRyRXpJY0ptTmE3dWcxb2FjSE9vdUkKLS0tIGZ1QmViWjRRcUZjVnZkZWdrQzU0
            dzg0eXlYakdSc2dmT3U0TEE2YmFUQXcKuqlJ0mb8mus6fzWvC2bChP/ycLJPMOrR
            djndqOYgk+Rk1Pvv3k0RMMJmJqDSwXO1Luv2fW1xipxLpDBomN6/8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:31:13Z"
    mac: ENC[AES256_GCM,data:ZGXFwx1LPbwIhsg+77LnGO+e9m9cAaJ+5inup7XToCGx/2fYq1Xy5K9QTla5+qtJtDDefGGlKy+l9dvgU1oHGy1M+JUOa5JNvprqjCcwiKLxSJQEOfTw23jgDfoDXYLXkskY/QYsL0/NHlIOgaJrTOWqRl/e0yU8DM/QlXTMrks=,iv:YglFx4zgUYW1ctGTZEpfVeAMyg06uybgD2MbFjty+so=,tag:zHxiMqt7urITLZif11lFWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
