apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:txbvU+slQosbcvZx5iNFneIAql8DJDsiJJVTDX4OMcvnYqLi,iv:vJ/8/F9cC640/3oVHv04ITpXWwhLnwJjKvP9fyW7xFk=,tag:3Ja+ZHNn7dztMugqRxpsSg==,type:str]
    credentials.json: ENC[AES256_GCM,data:6yvDkK+ePZxjEJ502WQaWeiq/ayZpS6URl9KtZWyflHKMkBSk9v0tuljflRqnu2QOWrM9diGxokEQxJR7TjmyQaLOoyQVetWSEMQ2hjlUafnuzFbsv14guravB3/kgOMP96PC67gagBIdAPwS508+xc0S5lOUyuQsvZgSkmuk1DCczm4gtgTVhqTPseuILm25nU5sae1IWL/MQzWQP/PTmFNwz/91B9ynUokvYe4Ww==,iv:1wTEM04on0KbwLbFSMSo4IprKda5FXyt4D4HCC4bSl0=,tag:SkPuegOVKi23ZDyn7U8d9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONzNabGxXaUpYM3MwcGZY
            MC9hN09QUEQxRUw5dCtqT1hHY1BCZ1psQWpRCmhMTndtTFN5V0Zwd3RXUWs5VndP
            NWRQK0pmMXhNejFiZWxzODR1UjJOcmcKLS0tIHlLQ255Q3l3OWxTZlZIM1dhS1I3
            a3lSUEdqelhtQVpUeUV0YUlEQVNZRXMKRAXfSsqLC/dXi6Jmg5hzhVr70E2FaeFm
            93oo0f0genmWkTsWTyF2NvwsI6BjHBi1pVxtZI2SkGT2asuNM08eWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:26:31Z"
    mac: ENC[AES256_GCM,data:CqLmofyGBywCci1M35+uOvOKs2hbjyO/q3qKhNRdv0Q0cSLyH2QAOkdhPqSDIApd0QOt8I4tgn7IYyo9MQrW2W0YwINKhy7o92nDJA9M50W4Z2XCiNhSjMKNLplG6/HHhcWNfhlUHJSOcVqOGf2vrJpv6mw26q2xR0X11Ym2vMY=,iv:bp3yZJyMYPUwiPzcOqo8tks6qCL5ZXL47xIWCj6clGY=,tag:+uvB7AluXAdGi7tOFlYNXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
