apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:umR8KIaMRwid58dmT68nZDT/vwd/papklN+Nm4vG271e5z0X,iv:ZUgSN9cjKrTZ+SQfqyir8HbzMNd36UKJt4uxVU/rfXY=,tag:sDduBC4Z9fv2Guaj3L8LPw==,type:str]
    credentials.json: ENC[AES256_GCM,data:cnEa5FW74SkfPZ2q7/7OWTlQCbylxFgc6nEePwprEUCWdjxfA38uK4n3JVWGjY4Rgc9CnBLLr8pSuFPdNmfS52gS+fWH2HWD9JgoaAut+qM4lkTcFpj+fxfZt37cMW4ROqH0TDACKIviRZtb+/YbmEt0z17YX1MXepky5qaifGSL0NtAjyCD871GKdo4yDjFcvnZ0KAVVh4pxmbVObVlq/fthUxvMp3JW/e1dQUetA==,iv:7Lh3NYT3j6Vhs3q+tEWArv+zGtbZLkOLAevKqx6wqpM=,tag:o60PcLxjBycnoE6Kn7s/GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUEVmOWh4ZGYwaG5Iakdv
            R1U5YnJCTlM1eW96emhWeHhxTnMreG90Vm40CisxTDNyR3U4VVFadXp6RW16andF
            SzZaaHpwVjJOT2dXRVBnejhlelJHNWsKLS0tIDZGSjg3NURYaVcwU3RUQ3p0bzNM
            NFRNdGh0dGlxVzRaajEzNGV3YmJ2Y2MKwrUSytBWss629a/brE+pF7EyJeLDysZx
            W3S5c8CFAZybDhHmqvSByWdK10dTKVG+woRv/8Em5OaXsEl50JJq5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T18:38:38Z"
    mac: ENC[AES256_GCM,data:sL450F3CnJbWnXae+AHyayIAs3m9f2PbC0HPeaCH0W1OFUiC773t7xJMOuroKcnnT+kkC3b2b8Ee8/Ly52bt/WNHzIhmDj9CpnYPyvaXGaYZMtJOjGxcb0qwXaP+53p77Af26jhIkwNPZ8a/tGJPbjz8dB620WZnAQrP4941+lk=,iv:HRKPXf3RTMYUctXNzD9MnkNdHPA5nVez+lQ2VRGoolk=,tag:JRaM1lMhphGD8l3mNi/CVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
