# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:75HvckztJXRaK29IlAuZnlRRR8UYchwmvZt5VSx5Q1T2ad3c1Vb9Nw==,iv:C/LoISD+9GmHP3Kc/37waDr4OD/R3qezCk3YI4N0l+k=,tag:7NRcmYVnSR1Tyh1lsu7FBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVnJwSEg4YzJpZDNwU3Bz
            MmsrR2wxNlBTMzFyNFNNMElUNXREQVVRaW1VClM4a1lSeVZjZ0NIbWh5RHA0L0d3
            ekVqUm5lR0d5b3BodXJPS0grRjE4a0UKLS0tIExacVg2Z0FnSm52SkI5Uys2clJ4
            UGpzcmQ5N2ZiZHk1S09kbmZSVHhnTGsKhdokN6abOWWJcXkqYCQ0vIII6qLdtnNT
            7sRAEjOBLi50ihcyx0OcP6+1DhOlowj+GjS+zbNOMNzjcE8qMwWnfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T16:23:16Z"
    mac: ENC[AES256_GCM,data:Y2U+YN7NRhTgsyZ7jkNNfNQzEhFxfP4FCjU+LuoWVpyYJvuyVIktxAGKCXaHp9gYeFwhDGFto+7dSp8IhzDexVs66ohMPBMBnsJXMnkt/R65zcVci4RPkHn8xcCqN0HuH8FfDRdv/t2t1Hrpv6IGWlieewpulqpddPK2juWOPdM=,iv:IySz6b+kb5c2ZiUpi0FxaRUp9Gjp2UFecWYAXmAvgv8=,tag:21/3EGSpH2oUdqB8aezHOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
