---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://pg-backup
    endpointURL: http://172.16.20.7:9000
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 17d
