apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  type: otel
  address: http://gateway-collector.observability.svc.cluster.local:4318
