# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:1mrNgwRFrtRzIvMSpPkMoDjY1BiRdNJB5lllsWlMUCo=,iv:D2Do2nj/HKwR9enqqUmr4uEEaq0pxCotGWMFpJlLdFQ=,tag:I7JB05li6iVr95B5tb/ONQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cExLOHdLamVmcDUyMEZ5
        SVRsczRnMXVwQWx0aTh1b2VuYU83MHNMZ0RzCnJKR29YVnA3MEhTdk9TcUs0cEZj
        Rm1YaUEyM09QQ1h5aG5qVnlsYlR2ZzQKLS0tIFdaYUJRMlBCbFkwTmdnTlI1QTJz
        Vk9UM1JTWjByekt5VGplT0VQVlJ0WHcKjRZcWjALydODIRGj9HIgZufttsvgjZ/2
        K/6p2ilU709rHTyNJPgT6ZQEUwdBrQSYjLMyhXiuqtpn2JyMlaphnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-20T12:34:51Z"
  mac: ENC[AES256_GCM,data:zs2HMKLlEzgcHZMzNy8iaU1IJNWndWOCI7iTp8QMMWWRUqgfLShqklBYPzi4VWtQeMJJ/CbCgBBAMqlgAB6d3IGAvzxbh+iSY67Ckyq0fY+4sidR3Cy1fbp40XlXEzZzS/a4i0tc97RYtm8u/k8LvLLOfeei78G/5Y2IxlFZyp0=,iv:k/ZcepHY1Kfgiyz+hmdbWO8RjfuSVX2+1u1HjaLCkaY=,tag:bMV6qv+b5R5gxVCgROpgFw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
