# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:hPvcdNMCpBr3GezV18Bd8SFB5oCixF+rLYNCGm9hYXM=,iv:HssWqTkMFj9Vt8lSvD8FoR38R6XRo91O/XV7SBAluLc=,tag:2Geh/MMJVMdF9JdGHNRPPQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkFldDRybmxTSktmcFhp
        d2RsTnI4cXQ5MTJOVUVlSEk0emZoZkoxaXlzCkg2Vi9OZmRnUmc3ZXZCT2svbkVt
        eWhTbXRxMHdpbk53cXAwN0ZnNDJqU2cKLS0tIGtORGhZRTg3VDVJcXRnU0lUZFB0
        dWE5ZzNIWFFYVy9FbnFHYlBmc1dEQUEK1vPduHi47smCROB8PS3GqhbUB9Lr6sR/
        iZ0COpuBuX3DXZo5x5qqM5M8xHH3M+9Vys0bGgyXPGuT5XBpugxhpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-19T17:17:54Z"
  mac: ENC[AES256_GCM,data:/Fvc0US25rXkHAN/GsJeOjFCL5PVeTsd6islQQ0z1o69q7xuWg3EQKzope8T5FIDYpVhfYPnKa+dSo9SeyemMHMpsDT6dSw9OgGkemCUu87d21MTMc2XujB85Ld+sFQE9h8HyjtL2gQM/h/90nxSq5J1tlLk9ot6GB8GJWfzKnk=,iv:aSjR0nI4ZuSYZsoarXOqDQQEjWZi4I++MInY1RCwcmc=,tag:uXMM5UlgfzgLZGSFEwRGHw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
