---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: volsync-cold-snapshot
spec:
  schedule: "${VOLSYNC_CRON_REMOTE='20 3 * * *'}"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: volsync-restart-${APP}
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile: { type: RuntimeDefault }
          volumes:
            - name: scripts
              configMap:
                name: volsync-cold-snapshot-${APP}-script
                defaultMode: 0755
          containers:
            - name: cold-snapshot-restart-controller-${APP}
              image: ghcr.io/fhoekstra/kubectl-shell:v1.36.1-1
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: STATEFULSET
                  value: "${STATEFULSET:=${APP}}"
                - name: PVC
                  value: "${CLAIM:=${APP}}"
              command:
                - /scripts/cold-snapshot.sh
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              securityContext:
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
