# JSON6902 patch for the shared ARC runner base
- op: replace
  path: /metadata/name
  value: home-ops-runner
- op: replace
  path: /spec/values/githubConfigUrl
  value: https://github.com/RonaldPhilipsen/home-ops
- op: replace
  path: /spec/values/template/metadata/labels
  value:
    app.kubernetes.io/name: home-ops-runner
- op: replace
  path: /spec/values/template/spec/serviceAccountName
  value: home-ops-runner
- op: replace
  path: /spec/values/template/spec/volumes/0/secret/secretName
  value: home-ops-runner-secret
