---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app matter-server
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  uninstall:
    keepHistory: false
  values:
    controllers:
      matter-server:
        type: statefulset
        pod:
          hostNetwork: true
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 7.0.1
              pullPolicy: IfNotPresent

            env:
              TZ: "${TIMEZONE}"
              MATTER_SERVER__INSTANCE_NAME: *app
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host matter.${SECRET_DOMAIN}
              MATTER_SERVER__LOG_LEVEL: debug

            resources:
              requests:
                memory: "100M"
              limits:
                memory: "500M"

    defaultPodOptions:
      securityContext:
        runAsUser: 0 # Must be run as root user
        runAsGroup: 0
        runAsNonRoot: false # Must be run as root user
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 34
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: *host
          lbipam.cilium.io/ips: 172.16.20.132, ${MATTER_IPV6}
        ports:
          ws:
            protocol: TCP
            port: *port
            primary: true
        externalTrafficPolicy: Cluster

    route:
      app:
        hostnames: ["matter.rphilipsen.nl"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        type: nfs
        server: 172.16.20.7
        path: /config/matter-server
