apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:txYSdY6pOhsG4O2IMkEWT4zaa3vq1/7F+n51w3SIlpO7c6WKVoCbNQ==,iv:kuFpVNHWFsVr6DKDyq9eJ6YFo60escf065tSNcnSzwU=,tag:S2byMzIr/XdQ3q1lNd2Gyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLakoxa3lYQk53d1hoTUZm
            b1lkL1Y5QktFZXNhQUF4M3pxUWVRYVBEcVg4CkttYnhwRGNtZytmZTk0dzhxaG5N
            RmFuWExFVk5oWldQR2k0cktWUFFVYTQKLS0tIGhSTklad2ZHRWV1MjNXQWlHdjBG
            enArODdZM1o5MlpnREU0ZHdCN083MWMK4YXQ0+t2IUAZ61Y051+AZDaSzdWnsLD4
            bBJkFjjiac2NbXPKtq5KqOQaUcOogY3NTRoZ5yAWujhZYntmkF2lFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:31:13Z"
    mac: ENC[AES256_GCM,data:SVZ0CUkFwwLuehVhMdJOFTYcOX8bNgzfS3V708MyKAzA2iJsHo1hh51iqLP3e6uHCtoLMWUu3y3wP8EFINNpBlH2UusjM2nH8sOguMkMo/bO47ebD8Pb02l9kev/0bjpF10cdy4/FJ//CuGjI3OGIHOrBjmuagyXZz+7yc01LPY=,iv:LNVSlwGoWz6QQtj1HSZmFeU/d/re3j90dYpV5qW1YOs=,tag:F/YMg8IeWWgG+N1KCaTWRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
