apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:8xVy/HQniuRBbccJpvLCGhLVM3uI+HWq2gWwv+7oDYSsUh65SHClKQ==,iv:pCRSEbaemOdKs9FAWDlLhAmIKEC9GeRSoRHzCYI3GB8=,tag:p3luRGsoiPxsa6w3kH45GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCenlOTW1qRWpEQW5Pb3FF
            Kzh5ZFREQUFtWFQ4QTJCZ3JVaU5ibldQQTJRClpEZ3Vmb0J3QUhmcVVsaHpEbit0
            elYzajZ1bUdyc3pYR2psTk90cDlTR3MKLS0tIFRKSFUybm1DUXYvdE5HSFVlL2ZO
            VVlGZFVhVlMzeXpJQzBoaXFVVTFyYUUK9rb9QUOl46WL15h3CdE+o+uP6kZ5BL1u
            SEfyG6k41FwmVUCqsjh+/m5TrOaFNwDdiEd+jzh3moHZ38Cdg+YkkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T18:38:38Z"
    mac: ENC[AES256_GCM,data:lBYiUj8nIwlaHK72LSK7+ap0pzvFXno5JgBfIKTAiHNZxz6r4mfpkQQHL05DZW7PBfFacg1f4o2f0LGWSEIAjb7dBU7h5RAiVBWG076WT2Ow3XdsgSDGtRJ7KUEIHA6x9mNBuOK9XHfcsiQDybHlxBsz8NOy13p9W6s6aFxcTXg=,iv:kzOsi2RmUTSahyw5Gnk3Sa8ZQLgQsUsaL2ctfOXEPv4=,tag:N5LoRczNihHgRXwczsicpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
