apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Pu04o565sw8LgTRvYRUesmtupiRpwMQbNeRT+s4ixiRRR4Zk3b+Kxg==,iv:NGNO4SHcQH/9NFDa2mJ2F0V7Zyew6Gm06v7lxmxnkSo=,tag:tmMIQ2386wRM299vp4p9EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU1daUVl1dEt3YmVSVFZ3
            RGtOQWtnOEovZVE4cjNLWmhlOElqWStLYkJRCi8wMVB5c3pIeXpvb1BrY1MwN1Rk
            cE8zTkpuVEJvQVYrTEdYNEYxZC90bWsKLS0tIHJYN1h0Z1FZLzFBTExORWx4RkFI
            Y01UM1BibnQyaU1sNyt5eVprMXBmYmMKzcRgfiojESB3Gvs87UocSRdo1eWk675P
            8k7L0Lt59zcGBv3lgyHOrDpeJQs/Tt3XhaK9FSfDFf5LSuchzd8e7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:26:31Z"
    mac: ENC[AES256_GCM,data:cg3a48hf3Fc61YZgj24zsaOyU59006KcQiHcGCbWAgjMzXcg2wRDHF9vuBzh3rSewyJbUVsBc7ZqlG38CRMfYDDBsPetqLXqLtImmaTG8N+UsB4MCclpHMOKg/clqH2jIAiI/NBtay4adpaEZi6bMrTKo/VDWijOeOzE/ejHW6I=,iv:jN5vtbRGqLeJeDB4BiDueiN1SIVPEjdquaRORfLy9VI=,tag:V2uen1iEkJ/q8/bjfg0L2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
