---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vernemq
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vernemq-secret
    template:
      engineVersion: v2
      data:
        DOCKER_VERNEMQ_USER_ADMIN: "{{ .vernemq_password }}"
        DOCKER_VERNEMQ_USER_SHELLY: "{{ .user_shelly_password }}"
        DOCKER_VERNEMQ_USER_HASS: "{{ .user_hass_password }}"
        DOCKER_VERNEMQ_USER_OTGW: "{{ .user_otgw_password }}"
        DOCKER_VERNEMQ_USER_SMARTEVSE: "{{ .user_smartevse_password }}"
        DOCKER_VERNEMQ_USER_SLEEPASANDROID: "{{ .user_sleepasandroid_password }}"
        DOCKER_VERNEMQ_USER_GAIA: "{{ .user_gaia_password }}"

  dataFrom:
    - extract:
        key: vernemq
      rewrite:
        - regexp:
            source: "(.*)"
            target: "vernemq_$1"

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vernemq-acl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vernemq-acl
    template:
      type: ConfigMap
      engineVersion: v2
      data:
        vmq.acl: "{{ .vernemq_acl }}"
  dataFrom:
    - extract:
        key: vernemq
      rewrite:
        - regexp:
            source: "(.*)"
            target: "vernemq_$1"
