apiVersion: v1
kind: ServiceAccount
metadata:
  name: "${APP}-cold-snapshot"
  namespace: "${NAMESPACE}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "${APP}-cold-snapshot"
  namespace: "${NAMESPACE}"
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "${APP}-cold-snapshot"
  namespace: "${NAMESPACE}"
subjects:
  - kind: ServiceAccount
    name: "${APP}-cold-snapshot"
    namespace: "${NAMESPACE}"
roleRef:
  kind: Role
  name: "${APP}-cold-snapshot"
  apiGroup: rbac.authorization.k8s.io
