---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-config
spec:
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            name: immich-config-tpl
            items:
              - key: immich-config.yaml
                templateAs: Values
  dataFrom:
    - extract:
        key: immich
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword-connect
    - extract:
        key: authelia
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword-connect
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-db-config
spec:
  target:
    name: *name
    template:
      data:
        JWT_SECRET: "{{ .IMMICH_SECRET_KEY }}"
        DB_HOSTNAME: immich-postgres-rw.database.svc.cluster.local
        DB_USERNAME: "{{ .POSTGRES_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        DB_DATABASE_NAME: "{{ .POSTGRES_DB }}"
  dataFrom:
    - extract:
        key: immich
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword-connect
