# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:jf+z2i2yFxhAOgOIwlmyE4TzK7Wlsp5qbaNi46qe1s58MfUvC9mXTg==,iv:tsUiJu2TPkpwab0qukJi1PB09baw0KKWr5Js1kRTatY=,tag:yswlzjDtJI3f9fXXsVFKCA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZmt6SkIvaCtqYlcxZkZO
        REx1Z0RTaVgyQkN4RnlsMkFZVDYrZUI4ZFgwCkQ2ZngvRTdMeTJCTXQ3L3d0ZmE0
        ZHNoRW5tS1ozd3lURndQNGo4QWhpVzAKLS0tIEhIaDg1enFWbVlheUhTSVhCOG50
        TWl1UmhWZ1NTMzhLZDBFTWlBeHplZzAK2xyGYFWyIRbD3qwMzmScf3oqDfCWJ69j
        NystpFSwFRdtY+2yGisCo9P+mNUxLjlUbPXuZk2D+MPCq8FbCmU5MQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-20T12:34:51Z"
  mac: ENC[AES256_GCM,data:mcIIMBIrHRh9ApDTmQwSpCOxw4oNC4QNkhIegaeeSRM0XBuubP/cTkzufbFSz921Q3d1TOA0VcPcEBwyaH2agAFPKHguvhtWpbt1hE/z1rpvbMdDBmjamw3EOi6tXTOeQkSUszo+o7/hw6eRT9yA9oh+emnMPWLqElvU5N6gLa4=,iv:6sQe543Ht0zCZ+arg+JWdfhbnERoIshNuc+3XXyO78g=,tag:nD6uIwVcl45VP4DuLfQh1w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
