# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:FYCg1M3A+G85CgtJFZGwztXG12grGF6tCusBIju/RQovJP01rKXxKw==,iv:+GaWbfVYsdpBhSR8/bvnPBwSECsdGYqhVyIZBEmERi4=,tag:eRIMKpDBnVDJfwAn4U3O4A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYTIvM2t4MzJXczEvMnRo
        RldBcGpMcDM4QVdEekYrVFpqRDM0VGUvT2tBCkFLTEhjMGtobmtYRlN5SExjODN1
        MzRGRXMwSTZnYlpKUHhxSXRmTjAwMVUKLS0tIDd4eUVwWktNOHlPNEFmaGc2ei8w
        eDZacHdLcWNZNWhnbmJ2Z3dHM2dlRlkKKWIDIYJd2xWD/472bDnoZ/5Pky7vlhfj
        SgNBpBvJ+mEhDmp0tdH+Fdo+dm4Fl8ZyGEkwcdsjK3gJEskS7INQ2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-19T17:17:54Z"
  mac: ENC[AES256_GCM,data:WKDOw+5czz57Jjw8lYswpNdi4LRwpKr/u7ZtUxA6WzRRbzq4vKe/C0WZWuqFGR2vDVB7kvoe8UDdAPXhL9rlpVdTr8G+57y8vss1PR0vHNOMHlJoPwuk2FKjScqzZYpwnH9B/rgvuWv5/eKVOgoT96QmOrpQ+0eh5vwH1iKzwp0=,iv:4ljF4LEagSB3bzrFKRTcvz08A69ayGLyVKne4yKwv6U=,tag:fh1WaSSCuXkan9tNxvOzYw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
