[global]
server_name = "rphilipsen.nl"
address = ["0.0.0.0"]
port = 8443

log = "info"

# DB settings
database_path = "/data"
database_backup_path = "/backups"
database_backups_to_keep = 1

rocksdb_compression_algo = "zstd"
rocksdb_compression_level = 32767
rocksdb_bottommost_compression_level = 32767
rocksdb_bottommost_compression = true

# Perf tuning
cache_capacity_modifier = 2.0
max_request_size = 20971520

# DNS Optimisation
dns_cache_entries = 1_000_000
dns_timeout = 60
query_over_tcp_only = true
ip_lookup_strategy = 1

# User settings
allow_encryption = true
allow_federation = true
allow_registration = true
new_user_displayname_suffix = ""
suspend_on_register = false

# Harden
allow_public_room_directory_over_federation = false
lockdown_public_room_directory = true
require_auth_for_profile_requests = true
trusted_servers = ["codestorm.net", "starstruck.systems", "unredacted.org", "matrix.org"]
query_trusted_key_servers_first = true
query_trusted_key_servers_first_on_join = false

[global.ldap]
enable = true
ldap_only = false
disable_tls_verification = true
uri = "ldap://lldap.security.svc.cluster.local:3890"
base_dn = "dc=rphilipsen,dc=nl"
bind_dn = "uid=continuwuity_bind,ou=people,dc=rphilipsen,dc=nl"
bind_password_file = "/secrets/ldap-bind-password"
ldap_filter = "(cn={username})"
uid_attribute = "cn"
name_attribute = "displayname"

# Additional config
[global.well_known]
client = "https://matrix.rphilipsen.nl"
server = "matrix.rphilipsen.nl:443"
# rtc_focus_server_urls = [
#     { type = "livekit", livekit_service_url = "https://livekit.rphilipsen.nl" },
# ]

#support_page =
#support_role =
#support_email =
#support_mxid =