# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.16.20.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.16.20.20"
  - "k8s.rphilipsen.nl"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-neo-alpha"
    ipAddress: "172.16.20.6"
    installDiskSelector:
      serial: "S64HNN0Y423517"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c15e36e1977b9a2d29b475ab90219e55d9c18a05985e33b244066ef9d1f7152a
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:7e:bc:c7"
        dhcp: false
        addresses:
          - "172.16.20.6/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.20.1"
        mtu: 1500
        vip:
          ip: "172.16.20.20"

# Global patches
patches:
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-openebs.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"
    - "@./patches/volumes/volumeconfig-k8s-neo-alpha.yaml"
