# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.16.20.2:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.16.20.2"
  - "k8s.rphilipsen.nl"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-alpha"
    ipAddress: "172.16.20.3"
    installDiskSelector:
      serial: "S36ENX0J920477"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/8f0be96362d30b90d391b8044ca9389670e270d066b0e4b243f1f2046f811c2f
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:d3:fa:c2"
        dhcp: false
        addresses:
          - "172.16.20.3/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.20.1"
        mtu: 1500
        vip:
          ip: "172.16.20.2"
  - hostname: "k8s-beta"
    ipAddress: "172.16.20.4"
    installDiskSelector:
      serial: "S36ENX0J914002"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer/8f0be96362d30b90d391b8044ca9389670e270d066b0e4b243f1f2046f811c2f
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:d3:f8:36"
        dhcp: false
        addresses:
          - "172.16.20.4/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.20.1"
        mtu: 1500
        vip:
          ip: "172.16.20.2"
  - hostname: "k8s-gamma"
    ipAddress: "172.16.20.5"
    installDiskSelector:
      serial: "S36ENX0J909876"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer/8f0be96362d30b90d391b8044ca9389670e270d066b0e4b243f1f2046f811c2f
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:d3:f6:d8"
        dhcp: false
        addresses:
          - "172.16.20.5/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.20.1"
        mtu: 1500
  - hostname: "k8s-delta"
    ipAddress: "172.16.20.6"
    installDiskSelector:
      serial: "50026B73831CDD8A"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer-secureboot/8f0be96362d30b90d391b8044ca9389670e270d066b0e4b243f1f2046f811c2f
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e20:7c:14:f4:83:26"
        dhcp: false
        addresses:
          - "172.16.20.6/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.20.1"
        mtu: 1500
        vip:
          ip: "172.16.20.2"
# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-openebs.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"

