apiVersion: config.talstomize.dev/v1alpha1
kind: Talstomize

clusterName: kubernetes
controlPlaneEndpoint: https://172.16.20.20:6443
kubernetesVersion: "v1.36.2"
secrets: ./talsecret.sops.yaml
additionalSubjectAltNames:
  - "127.0.0.1"
  - "172.16.20.20"
  - "k8s.rphilipsen.nl"

nodes:
  "k8s-neo-alpha":
    ip: "172.16.20.6"
    kind: controlplane
    installer:
      talosVersion: v1.14.0
      schematic:
        customization:
          systemExtensions:
            officialExtensions:
              - siderolabs/amd-ucode
              - siderolabs/amdgpu
              - siderolabs/iscsi-tools
              - siderolabs/realtek-firmware
              - siderolabs/thunderbolt
          bootloader: sd-boot
    patches:
      - machine:
          install:
            diskSelector:
              serial: "S64HNN0Y423517"
            wipe: false
            grubUseUKICmdline: true
          network:
            interfaces:
              - deviceSelector:
                  hardwareAddr: "58:47:ca:7e:bc:c7"
                dhcp: false
                addresses:
                  - "172.16.20.6/24"
                routes:
                  - network: "0.0.0.0/0"
                    gateway: "172.16.20.1"
                mtu: 1500
                vip:
                  ip: "172.16.20.20"

  "k8s-neo-beta":
    ip: "172.16.20.5"
    kind: worker
    installer:
      talosVersion: v1.14.0
      schematic:
        customization:
          systemExtensions:
            officialExtensions:
              - siderolabs/intel-ucode
              - siderolabs/iscsi-tools
              - siderolabs/realtek-firmware
              - siderolabs/thunderbolt
          bootloader: sd-boot
    patches:
      - machine:
          install:
            diskSelector:
              serial: "I258060859"
            wipe: false
            grubUseUKICmdline: true
          network:
            interfaces:
              - deviceSelector:
                  hardwareAddr: "00:90:27:f3:00:d0"
                dhcp: false
                addresses:
                  - "172.16.20.5/24"
                routes:
                  - network: "0.0.0.0/0"
                    gateway: "172.16.20.1"
                mtu: 1500

patches:
  - ./patches/global/machine-files.yaml
  - ./patches/global/machine-kubelet.yaml
  - ./patches/global/machine-network.yaml
  - ./patches/global/machine-sysctls.yaml
  - ./patches/global/machine-time.yaml

controlplanePatches:
  - ./patches/controller/cluster.yaml
  - ./patches/controller/machine-features.yaml

workerPatches:
