apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N94iq4dUTd+YNoA5YQ==,iv:3c6eGKGdwUlPRrBzWvi4lFQVQ2WOiOEInQQJKp3Pf2M=,tag:mSkF2n1eyMnxsrRxXN+Qpw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2WB/+LJOIBAu0onif0KdfzUnLYFO,iv:YHQlD/RHDrbQNzULz9imjizzfM8JNnP9tFtzdwP3cSQ=,tag:lUmSlh871rrSfmDlQtcZtA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xGuMrnuUCPPr0XJ8WO1tx24xTknLq2GYGNdGDO8GO1HJho7L,iv:wiY8UuvunVY2LxObGj5xwS4rU6IiQV3aAvC6koDySQw=,tag:SgHe6mHEO0AQZTWRRLGbrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQW5xT2pOY3AwL0lnT2Jr
            Z0R5ZTVsNEhVM29qcmNmYyt6VFppOXBGa25NCmlTZ0h3MWJRZU1TU3lEWW5qbC9F
            ZVhwNjJJRFA4cStsb2hpTVFxSG9NZ2MKLS0tIFcyQlVwL28vQ0RFZG9FY2FXWjU0
            V2FTVmJhMHZGVTVMUjRuUGVWSnhUY0EKVm/UW1jV3yMyV2YEIjoiAqEOO1X6kjha
            2HJMmTpPXxs8KsYN0sv0zx/s50A41j3GBkmjztvbuE4vBIXQnZGniw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T18:38:38Z"
    mac: ENC[AES256_GCM,data:VdkaBhcGHyXSG20j6XQCZ5eHeZmOHdYUhhMT8bj0KJ2ETOkRpH6BpcT+L5+vKfZ5vmgxmU3XSHh+rG0Xi6p/UyaiQkOgVXGGlEP6c7egJik1eCrHv35yDzrV78ERU/Z7sBEk6RjahtYNddcSCBfdAvgh9xC9f6XB99IM1jS6EaI=,iv:rRkDH16xXYgCl6QEhI2bJfzZjM6AMkH0xOqdeXyyJhQ=,tag:ZdiGv+aOJlFLZtdQI7pZIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
