apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jAJgkW0RWXqknOnZqQ==,iv:nKhGxxCBKlDgjfeKVUoAAYxX01QR2TQKxqZf8nssF90=,tag:RICLnAVJqIVi7hcZhLUU2Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:SvRXvmu4AoWiMavhLjL1XaAcOAaA,iv:wOdIwy8oEWvwABIF0SNtEkkmAb3Gxl+1JQbDQpYj/JE=,tag:QAWa9rQB7xcdANk6uz2KuA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IbCbFyvB2kUM+mjGH50vbx+BCyJtoL5ZOltr69vSOC9BGQSN,iv:Q+f92QMVKsSAUd3Ftu1XUxiGSrelYcrjMj+Ymy6M1+0=,tag:vsZDhCY+LZMa63ZOxMwWWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMFFnZ2RXQTB1Z1BKeCtJ
            Rm8zTi9hTnBpMUhOcmVCZ3NramRRWVZSZEdjCmZzVmlhU0d5SHhCWm5uTGxsQTBi
            V2hsZ0dHNGVXN2FvY0JkdURYcEdscEEKLS0tIEJEYVA0Y0VBQ3lKaTJjZ21QR21q
            bVpMUitJbGc1THBhUWc1WUNWdTVDR0EKQ/XMtgsXIbZ9I8bcxVLDLszJuPX/5h8r
            wCqKgEe9MRYdolTrSNBUyI7Tw0lr7zSbkoAns++YwXyaoTjP00igiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:26:31Z"
    mac: ENC[AES256_GCM,data:RXuzaWtA8L1fSZss0u1crNlS0zCQ/EXg+aW+W256rJZHzIrF/xsATHrm25pHYcxuEDghUEXwgA80y9XWbPu2g5hKOPxx0zvQjuBe1C3AylpkctWb44VQ+3jy4nhA3/7+3yV7goYS+7yvV5vZSbeXvKTsTYqgwdQLu3YRL1X6DvA=,iv:H65AjK3uSNlxgI63211YtgHcZFfjTvjNOBrfovKhFWQ=,tag:DGMs3fKvh9W5VTASpNQ2Ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
