apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jWC750iaItUfbEZBRg==,iv:zj7/ukTu7jKwmYGInC67LIqfKZLFupwfNYDmNaa8sQQ=,tag:hPKnfrjCsdMZ6Ta0bZyiUQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XTU4sk4mnaAHnlyG55+DHqtt1on+,iv:Kzzox+Q1F2VO53xW63mTKHtn2N1HhrgjE7wNS0jI3U0=,tag:u7jlCh1sUThGxq/0L7MKbA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:JSnJp0v47fjZnKxFBn5AfZNI1vQL4HcvYnRdPZr+VPikukio,iv:3H0y5EdG89kkGzQa7R7tIQAxc+kZNrCe2OYQ4Zyy7H8=,tag:quUL0n8Kh1tUc9s9qu7/7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc2FQWkF5cTJVcGZBUWtE
            dG12emd5Nk5qSGJ4VytPbVVaUVZzVGd2SlVjCkNLKytGY2tibUhMeEN5cEdIOFFI
            RGpFNjFJWlBGeDZSTUExWnZtN25xN28KLS0tIFBHR3IwY0t2Z1hRZkc4NTYvbnNm
            YkE4b2d0VzVwaGt3T0tYRnljR05GeEkK2TUFbwHSgWdUv8v1C/90Vt7ehYDoklBO
            yI6QrMrmzDH6xsUcaKnIeUPkoLV6fSPDVrmnGCDWYgcfEm0d5f+ErQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:31:13Z"
    mac: ENC[AES256_GCM,data:APxwDzntzp89+PyzZ4BlRvGFqjm2I8fz1ehpSkIbxnqqwPWEEIiycaak+72AjSZqFrZ4LlCrYzEXfL3YLafWyVVtqxdzmJBxHZLR2Q9oaOD6Ix6hWHQW2VIqVW6VKmFjAcv1jyUDYIFZk5ZL5Jwn0Rs3gtyHFL/jGZTIrHvzsLM=,iv:WSToVpZyD6NxfCnpibS040IGzPjbAcJ31zkai5pE0F8=,tag:JC7XlcJHHwDX1O6NBjoF+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
