---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 172.16.20.7
  - address: 1.1.1.1
  - address: 1.0.0.1
searchDomains:
  disableDefault: true
hostDNS:
  enabled: true
  forwardKubeDNSToHost: true
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local
podSubnets:
  - 10.42.0.0/16
serviceSubnets:
  - 10.43.0.0/16
