---
apiVersion: v1alpha1
kind: KubeletConfig
image: ghcr.io/siderolabs/kubelet:v1.36.2
config:
  serializeImagePulls: false
extraArgs:
  max-pods: "200"

defaultRuntimeSeccompProfileEnabled: true

---
apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
    - 172.16.20.0/24
