apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: "${APP}"
  namespace: "${NAMESPACE}"
spec:
  policyRef:
    name: "${APP}"
  schedule:
    cron: "0 * * * *"
    jitter: 30m
    runOnCreate: false
