# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: "${APP}"
  namespace: "${NAMESPACE}"
spec:
  repository:
    kind: ClusterRepository
    name: kopiur
  identity:
    username: "${APP}"
    hostname: "${NAMESPACE}"
  sources:
    - pvc:
        name: "${APP}"
  copyMethod: Direct
  compression:
    compressor: zstd-fastest
  upload:
    maxParallelFileReads: 2
  retention:
    keepHourly: 6
    keepDaily: 1
    keepWeekly: 4
  mover:
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
