---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: longhorn-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .LONGHORN_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .LONGHORN_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: http://172.16.20.7:9000/
        VIRTUAL_HOSTED_STYLE: 'true'
  dataFrom:
    - extract:
        key: longhorn
