apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WCLk3sDS1Qpx+EFMvcodbsYz2a80aMXjp64QnXJb1ik=,iv:2A4jkGfOdUw/QPpNKc3OcwytTzpPRYfGI8ZqmfZCU3s=,tag:4uYqNInxi074HkaRZaAzZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN1FtUWVVUUx2eENsK1lK
            WThGVFFPN2VGV2RQalZZNEVQSjVwQVNCdmhvCnZqSDR3RFJ3V0xsZWxreVArbWxO
            MHZFa1RuejErdUtNeXZaNGMvWHY3amcKLS0tIGtPT1RqOGhZMWdYOFYxVjI2NXZW
            OE1XMjZ6ZDIybjRNTzlVVUdQdGtja3MKeHI2Eud+76ql6LQRuRNVfx916ZkQeNF+
            kgCXPAvYoerVPH99p8qGhPC8EkGDJkkvT5cbs8wmsBtRV6vVju3XSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:31:13Z"
    mac: ENC[AES256_GCM,data:OqZAzpdOZ0gKDujTSyUzkHYVSwrcgboqTJepDQhTub+56GY6E6ra1sRxKqTdzHZl/PLiDR3vgVaJkRkw9CRldkux6Q470PbN2YYDHMiimd9s7t9dALWFh9BqULOBNx8VCtmZOIejEdzT/rd2N/CErF8PdQNDfvNUZI2VFgSltsM=,iv:hX0o3oZOgRgk+lSSl7GINdItAlG46JQ+bzuiJtQIy48=,tag:YxPmBkxeAJ1nks/DGrrUcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
