apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Iv6i/pbmH2Qqv5ARXI3wLB2AWa3ZQqq9Ts3JtBn27sA=,iv:WOzdpv3p5lfTgSNJKEnTPKHXSO8ShWHX19JNspRXXs8=,tag:rQW+PSmScRuIhEtBPeGU1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTC9TckZwajE4aEQvY2Zk
            SHJVV2RsclpGZlFnMWFUb3BpTWNHZkpsNG5zCmxIZlhkWmY3UGlBRmxjbW1paUg2
            YmY3RGJzZ1BaeEVpU2pWRlErOHFDSWcKLS0tIFZpREFUQnk0S1F6c1JCYkVZa29l
            OUZXajRaOUN5MzFyRFQ5VjlVOEE1UHcKfC9fyQo4CWXoggHPu4E/UwUu8l6NvUuC
            lsswf3KJES+uF2RiWvdCwbIFxEHGZaai2s3nlmNo6dON25uwGJtJoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:26:31Z"
    mac: ENC[AES256_GCM,data:eOi2y+8/kpMr/+GPy75J+XeiTGDxvd2yDasQrJQj7gYoAq5/FcO5B5wNvevTd38c4EBx0pN/iNaYvbCTmfrRZuwXjr5t6cYDF/On+agjUeOX2gtxqH0T0jQkAl9Mtls2wrEFbfcRXnO72XEmhzZ9cCHvs0AuweEPWo8hcP5EF5Y=,iv:F7Ol+JLfxVKJTr++vAdd0qVNd5rQmR3qJ/QxcfhPrZk=,tag:LqXLuUvU/76KRldWwzED9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
