apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:bQmzjhkpo/FKXmK/+hbpLNbVgl0PRvqOcgPPuiHTxsE=,iv:+YGLNzb8fwhGJk31ETspmgMFpEp8+8SjtR8FwKvxcAA=,tag:1OMVe4N4rcf37UtpD0+tFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGR0bHdTNW9kamNkNkIv
            cnNJL0hGMlljanMvSmlXNDFZWUxLRFlhQUNRClk3eXBxWDVnTFVuVnM2U2FLOTNG
            bDhXVTduckNOdWtweGdKejZQL3pPZmMKLS0tIE9sZXdzbEZZbkt4QVorN2Zva0Iv
            cVVNYVhrcjZyb040N0x4TmNNL2NNWGsK+1d4E9ofOr6OTLJnrl780CCl5+PcYOah
            pY5M8G1ewZ85sNJrYtoyQeyvhQ2Ba7BgAE53rssGxLwNpfoLhjGn6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T18:38:38Z"
    mac: ENC[AES256_GCM,data:XKDaktDGrB7BGGRDL8hnMD2P2tDaHL83kA+WJV58lA0ombQPeG/36ODhaJVT9A1j2X+3cSq2d1ILQtpzE7aoSGu3j6w2DpjygGUSEMp9bu5Gd/K7VP74T1hO3GACXb7s4qzN/HFVb9qAyOGFSLR7QbRXjHlGx4giyjKMOz0/5ag=,iv:d6WpKEYw88G2M03SICMRN9kL0S3xowVpd218OdUPRQw=,tag:RFNnjJoLfklwSoI8p14eQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
