---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.8.3@sha256:7ef14f513e487add292b43306cccb4f1cd9dbcbd5eaf85d6438f98b197f930a4
            env:
              TZ: Europe/Amsterdam
              HASS_HTTP_TRUSTED_PROXY_1: 192.168.0.8/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.69.0.0/16
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8123
          coiot:
            port: &coiot 5683
      lb:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 172.16.20.130
        ports:
          coiot-udp:
            port: *coiot
            protocol: UDP
          https:
            port: *port
            protocol: TCP
    route:
      app:
        hostnames: ["home-assistant.rphilipsen.nl", "hass.rphilipsen.nl"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: rphilipsen-https
        rules:
          - backendRefs:
              - name: home-assistant-app
                port: *port

    persistence:
      config:
        type: nfs
        server: 172.16.20.7
        path: /config/home-assistant
        globalMounts:
          - path: /config

      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
