apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
spec:
  concurrency: 1
  cron: 0 3 * * *
  groups:
    - default
  labels: {}
  name: snapshot-cleanup
  parameters: {}
  retain: 0
  task: snapshot-cleanup
