apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5tHRti9s7zotpFIm9w==,iv:/HlHloYlhuaR05xyI6PPqSmupSFuw8uqYrjKT1NE0HQ=,tag:MDktqeoy7GByBDvg7Y/L0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVGJJaHdpVXJmY1VnVzIr
        aHBrY3NySmdkQjRpNXlaUEwvOExNVmdhVUc0CjVWWUptOXZGNHNoWWVSM1NGVlJZ
        bW0zRVdLakd6M1dqUk1LbFh3bWtoNzgKLS0tIHIxVnZ3RGtJWStOWjlMOHAxYU02
        NFk3T1ErZ2F4SE02Ky9ieWxOd3RDMGsKuj9t1mhtwyTkxpW9K1HDHb6UVgu3+luB
        wzH6eyCfWqqx9D54A/h9S7Ls4S5i5eulJAhxnqPWNiHpAbMboQCiNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eyeengpqz4yn654cv5gn5xvdhqchxqp7uw6yvx4sql5mv28mvquqrdwmjy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T13:32:07Z"
  mac: ENC[AES256_GCM,data:GDDGIBa+zCes0eRSdPUXImk/5gcEfAPGMRsEfE6rXDpfxJ5B7VerYK7udyTG6uqvXjdo11mcpih+oz7XCKfJws9Qkl51iHrKKHwwf9v7EjLNk6VGmd5ELfyIiFI4eNTFedyfizBx0fg3L6cNvca1ppg9Fn0wUuOKNiiCu1syDbM=,iv:eH3H6v9ky/zKzjySo6JRHyWuQc+RaZyRAX6JAizh5Ak=,tag:yU6NFV7OLtw9a9lyVJzAJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
