apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:P49SxdhuaLeqdhnPUx7ovtrRr2v5gQEWDyh2FTF/HsSYSozAGkAX6g==,iv:wcE2QLtBvTWlqoac2iAD0ZTexZXNKULzUXARW6fDEZo=,tag:1J4Oo3rhvW6GORvg8Dj9KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UW1sSzNvckEwTzRqbVF6
            Wis2cTJhaGt4Rmo1RzFha09iWVFEd0JOVVFRCm1KZUZLTUUzcWMwUndYU09Gc0x4
            OWNSTStyVDV3WjJpZml4d056OVh0b1EKLS0tIG9SSnRzckdob2N5Qnk3SW5INUIx
            VEZCQnByUWQ5QlR2em5pY2REOWxkdmsK/gZGUcDKi7MuyhsZQ6vEWc2Hje0ejByS
            4X95WkFrzpk3D/Kkt9rB02y0PVk5XMCmymMoyLucgVIviIx0T4SHkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:26:31Z"
    mac: ENC[AES256_GCM,data:21FDHOkGfqp2vWz7UpCi7N8ArJlytsYH8lZ0S3moNkJXWxPCF5WGmXFxF6mtRlxzV/WZXlGCbNwwTXG0XFWLwSpNj4QOdArxivCPeaJ3Mrgv+F9qh5SSOmYiLUFiYsiwcGOLN7ifQ+MNxtKkGt9zVsfvHbbDYPsrxCkyk7ey61Y=,iv:uyQw2XRwTpNYOHNEewZZpZikS1ajLIOhn8ZG4M1ZG0s=,tag:r/YHvufxA+QPjhBAqY3gAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
