apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:funmyOWsrQeLt+s2Rs5yum5STiOVu2g5PEJdJm1p2XQ1umsSM+yYJw==,iv:eRJXUSRzyDJ2GD/3pTPd+HbCYNTmd3bY17Pz7S4feSg=,tag:RBEKp1xqJqZyaE4PdaHp1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWE5aTlBZQndEdExnZHRn
            ZS9uZVhsSUttZ2JFNUZhNkFlUXRIanV4YVI0CmlEZGl5cElRQU5HSGNWY1ZORUt3
            Wnd2UEtjUmFrc2g1MXphT1Rzd0dRSVEKLS0tIFZ1ZEltY3NMMmM4NXY5QkFsc1VY
            TGZ0VmtyVFdCOENNenZvU0l2bTdVT1EKByPBVwmEHxJslnYdguGzyr2Au38JZnvQ
            0Z2FBwpOY/qLrPiJNcf5o/9c24KPIPcJHqkt/nKkdZ+UjRJSoRwCjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T18:38:38Z"
    mac: ENC[AES256_GCM,data:jWDDr2cZ1v6JbsJE1BqKEPsBpb5wZYSbB94uqIPAEN01x3kBlY+BaEo8+kY9xNHMM7c11VlD9oIhzwwx5bPRuqR6qSPgBhtnnJsSxiiBkCoBye0LYJubi8fYbT5ZmYzOAU3UVqWTcc5CenhX826FdC7vsovXx8y+nydo91K7Jbg=,iv:np4gITSoebXy8VVJS6nx0GKGQYoI+NhY0+qFk5SKTk4=,tag:mJ36JZqT4454gYR6ReKj3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
