apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4VJSiQN+b9U4ua6XxooXpT17BpWnforcaHHUlZwpyYf6pM7CweJzMw==,iv:Do9EeJVA/JMdF+ryi01/z/1unyeCj9fH8LH+uHYMcZs=,tag:uV0ZXuv9onm4QJ3ziezrLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150gafxycv6yhlgv8hanf9gl36apk76pq2rcxuj4vfyewdn7fxumspjhx9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdHFjbHh3dHVkdjZNUHhE
            Tm45LzZnWFlBYWZGTU5RekpEZDkwVHF3SnlBCktZRXJEb1c4TmIyWFBxR1RRcXQw
            ZU5oTGN6c1ZBbS9IVFI0bk9zYW9TcGMKLS0tIGd6YWJxdTRiZ1doaTdwdGhkdG5K
            TXJPZmI3NUJJcTlnMWw3SVpIbENTdzAKIIpU1GBjm65JQ1SbI15K2KGKqgaHIz5w
            IXr6teQIvj5t4FfoDUpmTMwbnPoLSD4D4DcDc8PSVGhl3ml3ljd7rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:31:13Z"
    mac: ENC[AES256_GCM,data:hG+FHE1AHJyEmIhAXZfZ/BeJcmyUrpEyXHtNgiKeqvOsUjgMfqASN5LVlbcFWukJs+gN8Cgm4Q5P5y3kW8sDGEpA202+sOcPeC5cito770XdDw6jZzRGF1pkbKswgieMzHz4Ca1jk9nKwbSEEYFVCWlL4PhoQzF7iGq97yGXShU=,iv:6kqrNAD0RFbCn+F4hcQpG6xGzg5s07M/VkFJdqmHQCs=,tag:oJ/K0kTdyk0YGLJZXun8ZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
