{
 "title": "Cloudnative coffee",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gaggiuino_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Machine Reachability (Binary Outage Map)",
   "type": "state-timeline",
   "description": "0 = offline, 1 = online",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "gaggiuino_up", "legendFormat": "outage" }
   ]
  },
  {
   "title": "Boiler Temperature vs Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gaggiuino_temperature", "legendFormat": "__auto" },
    { "expr": "gaggiuino_target_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "abs(gaggiuino_temperature - gaggiuino_target_temperature)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brew pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    { "expr": "gaggiuino_pressure_bar", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shot Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    { "expr": "gaggiuino_shot_weight", "legendFormat": "__auto" }
   ]
  }
 ]
}