---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: k8s-gateway
    files:
      - ./config/Corefile
generatorOptions:
  disableNameSuffixHash: true
